// Content for the trending party games (all family-friendly).

export const WYR = [
  ['Be able to fly', 'Be invisible at will'],
  ['Unlimited pizza for life', 'Unlimited biryani for life'],
  ['Live without music', 'Live without movies'],
  ['Always be 10 minutes late', 'Always be 20 minutes early'],
  ['Speak every language', 'Talk to animals'],
  ['A beach vacation forever', 'A mountain vacation forever'],
  ['No phone for a month', 'No meeting friends for a month'],
  ['Be famous but modest income', 'Be rich but completely unknown'],
  ['Time-travel to the past', 'Time-travel to the future'],
  ['Superhuman strength', 'Superhuman speed'],
  ['Only chai forever', 'Only coffee forever'],
  ['Live in a buzzing city', 'Live in a quiet village'],
  ['Read minds', 'See 10 minutes into the future'],
  ['Never do chores again', 'Never stand in a queue again'],
  ['Winter all year', 'Summer all year'],
  ['Be a movie star', 'Be a cricket star'],
  ['Pause time whenever you want', 'Rewind time once a day'],
  ['Sing everything you say', 'Dance everywhere you walk'],
  ['Free food for life', 'Free travel for life'],
  ['Lose the ability to lie', 'Detect every lie instantly'],
  ['Have a pet dragon', 'BE a dragon'],
  ['Open-book but very hard exams', 'Closed-book but easy exams'],
  ['Breakfast food for every meal', 'Dinner food for every meal'],
  ['A new phone every year', 'A new trip every year'],
]

export const MLT = [
  'become famous',
  'forget their own birthday',
  'sleep through five alarms',
  'become a crorepati',
  'cry during a movie',
  'eat the last slice without asking',
  'get lost even with GPS on',
  'make friends with a total stranger in 5 minutes',
  'become a chef',
  'reply to a text after 3 days',
  'laugh loudest at their own joke',
  'adopt five dogs',
  'start a YouTube channel',
  'win a reality show',
  'search for the phone they are holding',
  'dance first at a wedding',
  'reach the airport at the last minute',
  'become a teacher',
  'finish their salary in one week',
  'survive a zombie apocalypse',
  'say "5 more minutes" and sleep an hour',
  'take 100 selfies a day',
  'start their own business',
  'move to another country',
]

export const NHIE = [
  'pretended to be sick to skip school or work',
  "forgotten someone's name while talking to them",
  'sent a message to the wrong person',
  'cried during a cartoon',
  'fallen asleep in class or a meeting',
  'eaten dessert before dinner',
  'talked to myself in the mirror',
  'laughed at completely the wrong moment',
  'stalked my own social media profile',
  're-gifted a present',
  'sung out loud forgetting my earphones were on',
  'waved back at someone waving at the person behind me',
  'rehearsed an argument in the shower',
  'walked into a room and forgotten why',
  'photographed food before letting anyone eat',
  'binge-watched an entire series in one night',
  'pretended to have read a famous book',
  'danced like crazy when no one was watching',
  'called a teacher "mummy" or "papa" by mistake',
  'checked my phone even with no notification',
  'said "I\'m on my way" while still at home',
  'cooked Maggi at 2 in the morning',
  'clapped when the plane landed',
  'laughed at a joke I did not understand',
]
