// Content for the famous-format games: awareness trivia (9 categories),
// Wordle-style answers, Word Bloom puzzles, and emoji riddles.
// MCQ shape: { q, o: [4], a: correctIndex }

export const TRIVIA = {
  animals: {
    name: 'Animals', icon: '🐾', color: '#7EDD62',
    items: [
      { q: 'The largest animal ever to live on Earth is the…', o: ['African elephant', 'Blue whale', 'Giraffe', 'T-Rex'], a: 1 },
      { q: 'The fastest land animal is the…', o: ['Lion', 'Horse', 'Cheetah', 'Greyhound'], a: 2 },
      { q: 'The national animal of India is the…', o: ['Lion', 'Elephant', 'Bengal tiger', 'Leopard'], a: 2 },
      { q: 'An octopus has how many hearts?', o: ['One', 'Two', 'Three', 'Eight'], a: 2 },
      { q: 'Penguins are naturally found in the wild in…', o: ['The Arctic', 'The Southern Hemisphere', 'The Himalayas', 'Everywhere'], a: 1 },
      { q: 'A koala feeds almost entirely on the leaves of…', o: ['Bamboo', 'Eucalyptus', 'Neem', 'Mango'], a: 1 },
      { q: 'The national bird of India is the…', o: ['Parrot', 'Sparrow', 'Peacock', 'Eagle'], a: 2 },
      { q: 'The snow leopard is nicknamed the…', o: ['King of the jungle', 'Ghost of the mountains', 'Desert phantom', 'Ice tiger'], a: 1 },
      { q: 'A group of lions is called a…', o: ['Pack', 'Herd', 'Pride', 'Colony'], a: 2 },
      { q: 'A baby kangaroo is called a…', o: ['Cub', 'Calf', 'Joey', 'Kit'], a: 2 },
      { q: 'Which bird is famous for mimicking human speech?', o: ['Crow', 'Parrot', 'Pigeon', 'Owl'], a: 1 },
      { q: 'An elephant\'s pregnancy lasts about…', o: ['9 months', '12 months', '22 months', '3 months'], a: 2 },
    ],
  },
  movies: {
    name: 'Movies', icon: '🎬', color: '#FF5F8F',
    items: [
      { q: 'In Sholay, the iconic villain\'s name is…', o: ['Mogambo', 'Gabbar Singh', 'Shakaal', 'Kancha'], a: 1 },
      { q: 'Which film is famous as the longest-running in Indian cinema history (Maratha Mandir)?', o: ['Sholay', 'DDLJ', 'Mughal-e-Azam', 'Hum Aapke Hain Koun'], a: 1 },
      { q: '3 Idiots starred which actor as Rancho?', o: ['Shah Rukh Khan', 'Aamir Khan', 'Salman Khan', 'Hrithik Roshan'], a: 1 },
      { q: 'Titanic and Avatar were both directed by…', o: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Ridley Scott'], a: 1 },
      { q: 'India\'s first talkie (sound) film was…', o: ['Raja Harishchandra', 'Alam Ara', 'Mother India', 'Awara'], a: 1 },
      { q: '"Naatu Naatu" won the Oscar for Best Original Song from which film?', o: ['Baahubali', 'RRR', 'Pushpa', 'KGF'], a: 1 },
      { q: 'The Baahubali films were directed by…', o: ['Rajkumar Hirani', 'S. S. Rajamouli', 'Karan Johar', 'Sanjay Leela Bhansali'], a: 1 },
      { q: 'Lagaan revolves around which sport?', o: ['Hockey', 'Kabaddi', 'Cricket', 'Football'], a: 2 },
      { q: 'Which Indian filmmaker received an honorary Oscar for lifetime achievement?', o: ['Yash Chopra', 'Satyajit Ray', 'Raj Kapoor', 'Guru Dutt'], a: 1 },
      { q: 'The Marvel Cinematic Universe began in 2008 with…', o: ['Thor', 'Captain America', 'Iron Man', 'The Avengers'], a: 2 },
      { q: 'Dangal tells the story of champions in which sport?', o: ['Boxing', 'Wrestling', 'Weightlifting', 'Judo'], a: 1 },
      { q: 'The Lion King\'s young hero is named…', o: ['Mufasa', 'Scar', 'Simba', 'Timon'], a: 2 },
    ],
  },
  music: {
    name: 'Songs & Music', icon: '🎵', color: '#C77DFF',
    items: [
      { q: 'A. R. Rahman won two Oscars for the music of…', o: ['Lagaan', 'Slumdog Millionaire', 'Roja', 'Taal'], a: 1 },
      { q: '"The Nightingale of India" refers to…', o: ['Asha Bhosle', 'Lata Mangeshkar', 'Shreya Ghoshal', 'M.S. Subbulakshmi'], a: 1 },
      { q: 'India\'s national anthem was written by…', o: ['Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Premchand'], a: 1 },
      { q: 'The Beatles came from which city?', o: ['London', 'Manchester', 'Liverpool', 'New York'], a: 2 },
      { q: 'Pandit Ravi Shankar was a maestro of the…', o: ['Tabla', 'Sitar', 'Sarod', 'Flute'], a: 1 },
      { q: 'The Oscar-winning song "Jai Ho" appeared in…', o: ['Slumdog Millionaire', 'Life of Pi', 'Gandhi', 'RRR'], a: 0 },
      { q: 'The globally famous group BTS is from…', o: ['Japan', 'China', 'South Korea', 'Thailand'], a: 2 },
      { q: 'The tabla belongs to which family of instruments?', o: ['String', 'Wind', 'Percussion', 'Brass'], a: 2 },
      { q: 'India\'s national song "Vande Mataram" was written by…', o: ['Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Subramania Bharati', 'Kabir'], a: 1 },
      { q: 'Which legendary playback singer was also a famous comic actor (Padosan)?', o: ['Mohammed Rafi', 'Kishore Kumar', 'Mukesh', 'Manna Dey'], a: 1 },
    ],
  },
  popculture: {
    name: 'Pop Culture', icon: '⭐', color: '#FFD060',
    items: [
      { q: '"King of Bollywood" usually refers to…', o: ['Salman Khan', 'Shah Rukh Khan', 'Aamir Khan', 'Akshay Kumar'], a: 1 },
      { q: 'Kaun Banega Crorepati is famously hosted by…', o: ['Salman Khan', 'Amitabh Bachchan', 'Kapil Sharma', 'Aamir Khan'], a: 1 },
      { q: 'Priyanka Chopra won which title in 2000?', o: ['Miss Universe', 'Miss World', 'Miss India runner-up only', 'Miss Asia'], a: 1 },
      { q: 'Lionel Messi plays international football for…', o: ['Brazil', 'Spain', 'Argentina', 'Portugal'], a: 2 },
      { q: 'Sachin Tendulkar is popularly called…', o: ['Captain Cool', 'The Wall', 'The God of Cricket', 'Sixer King'], a: 2 },
      { q: 'Neeraj Chopra won Olympic gold in…', o: ['Shot put', 'Javelin throw', 'Discus', '100m sprint'], a: 1 },
      { q: 'P. V. Sindhu is a champion in which sport?', o: ['Tennis', 'Badminton', 'Table tennis', 'Squash'], a: 1 },
      { q: 'Mickey Mouse was created by…', o: ['Warner Bros', 'Walt Disney', 'Pixar', 'Hanna-Barbera'], a: 1 },
      { q: 'M. S. Dhoni is nicknamed…', o: ['The Wall', 'Captain Cool', 'Master Blaster', 'Hitman'], a: 1 },
      { q: 'Which video game character jumps through pipes collecting coins?', o: ['Sonic', 'Mario', 'Pikachu', 'Pac-Man'], a: 1 },
    ],
  },
  politics: {
    name: 'Politics & Civics', icon: '🏛️', color: '#38C6F4',
    items: [
      { q: 'India\'s first Prime Minister was…', o: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Sardar Patel', 'Rajendra Prasad'], a: 1 },
      { q: 'The lower house of India\'s Parliament is the…', o: ['Rajya Sabha', 'Lok Sabha', 'Vidhan Sabha', 'Gram Sabha'], a: 1 },
      { q: 'The minimum voting age in India is…', o: ['16', '18', '21', '25'], a: 1 },
      { q: 'The United Nations headquarters is in…', o: ['Geneva', 'Paris', 'New York', 'Vienna'], a: 2 },
      { q: 'India\'s first woman Prime Minister was…', o: ['Sarojini Naidu', 'Indira Gandhi', 'Pratibha Patil', 'Sonia Gandhi'], a: 1 },
      { q: 'The Indian Constitution came into effect on…', o: ['15 August 1947', '26 January 1950', '2 October 1948', '26 November 1952'], a: 1 },
      { q: 'The official residence of the US President is…', o: ['Capitol Hill', 'The White House', 'Pentagon', 'Camp David'], a: 1 },
      { q: 'The head of a state government in India is the…', o: ['Governor', 'Chief Minister', 'President', 'Collector'], a: 1 },
      { q: 'Who is regarded as the chief architect of the Indian Constitution?', o: ['Nehru', 'B. R. Ambedkar', 'Patel', 'Rajagopalachari'], a: 1 },
      { q: 'Elections in India are conducted by the…', o: ['Supreme Court', 'Election Commission', 'NITI Aayog', 'President'], a: 1 },
    ],
  },
  history: {
    name: 'History', icon: '🏺', color: '#FF9F2E',
    items: [
      { q: 'India became independent in…', o: ['1942', '1945', '1947', '1950'], a: 2 },
      { q: 'Gandhi\'s Salt March (Dandi) took place in…', o: ['1920', '1930', '1942', '1947'], a: 1 },
      { q: 'The Taj Mahal was built by…', o: ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Humayun'], a: 1 },
      { q: 'Emperor Ashoka embraced peace after which war?', o: ['Panipat', 'Kalinga', 'Plassey', 'Haldighati'], a: 1 },
      { q: 'The First War of Indian Independence broke out in…', o: ['1757', '1857', '1885', '1905'], a: 1 },
      { q: 'Harappa and Mohenjo-daro belonged to which civilisation?', o: ['Mesopotamian', 'Indus Valley', 'Egyptian', 'Vedic'], a: 1 },
      { q: 'The Wright brothers achieved the first powered flight in…', o: ['1893', '1903', '1913', '1923'], a: 1 },
      { q: 'World War II ended in…', o: ['1918', '1939', '1945', '1950'], a: 2 },
      { q: 'The Indian National Army (INA) was led by…', o: ['Bhagat Singh', 'Subhas Chandra Bose', 'Lala Lajpat Rai', 'Chandra Shekhar Azad'], a: 1 },
      { q: 'The Great Wall was built primarily to protect…', o: ['India', 'China', 'Persia', 'Rome'], a: 1 },
    ],
  },
  economy: {
    name: 'Economy', icon: '💹', color: '#4ECD7A',
    items: [
      { q: 'India\'s central bank is the…', o: ['SBI', 'RBI', 'NITI Aayog', 'SEBI'], a: 1 },
      { q: 'GDP stands for…', o: ['Gross Domestic Product', 'General Development Plan', 'Gross Daily Profit', 'Global Domestic Price'], a: 0 },
      { q: 'A general rise in prices over time is called…', o: ['Deflation', 'Inflation', 'Recession', 'Stagnation'], a: 1 },
      { q: 'GST was rolled out across India in…', o: ['2014', '2017', '2019', '2020'], a: 1 },
      { q: 'The Sensex tracks shares on the…', o: ['NSE', 'Bombay Stock Exchange', 'RBI', 'World Bank'], a: 1 },
      { q: 'The Union Budget of India is presented by the…', o: ['Prime Minister', 'Finance Minister', 'RBI Governor', 'President'], a: 1 },
      { q: 'A market where prices keep rising is called a…', o: ['Bear market', 'Bull market', 'Flat market', 'Black market'], a: 1 },
      { q: 'The ₹ symbol for the rupee was adopted in…', o: ['1991', '2000', '2010', '2016'], a: 2 },
      { q: 'High-value notes were demonetised in India in…', o: ['2014', '2016', '2018', '2020'], a: 1 },
      { q: 'The organisation that replaced the Planning Commission is…', o: ['SEBI', 'NITI Aayog', 'IRDAI', 'NABARD'], a: 1 },
    ],
  },
  culture: {
    name: 'Culture & Festivals', icon: '🪔', color: '#E1595C',
    items: [
      { q: 'The "festival of lights" is…', o: ['Holi', 'Diwali', 'Onam', 'Pongal'], a: 1 },
      { q: 'The festival of colours is…', o: ['Diwali', 'Holi', 'Raksha Bandhan', 'Navratri'], a: 1 },
      { q: 'Bharatanatyam originated in…', o: ['Kerala', 'Tamil Nadu', 'Odisha', 'Manipur'], a: 1 },
      { q: 'Bihu is the beloved festival of…', o: ['Punjab', 'Assam', 'Gujarat', 'Bengal'], a: 1 },
      { q: 'Onam is celebrated mainly in…', o: ['Karnataka', 'Kerala', 'Tamil Nadu', 'Andhra Pradesh'], a: 1 },
      { q: 'Eid-ul-Fitr marks the end of…', o: ['Muharram', 'Ramadan', 'Hajj', 'Shab-e-Barat'], a: 1 },
      { q: 'Kathakali, with its elaborate face paint, comes from…', o: ['Kerala', 'Odisha', 'Manipur', 'Rajasthan'], a: 0 },
      { q: 'Baisakhi, the harvest festival, is central to…', o: ['Punjab', 'Bihar', 'Goa', 'Sikkim'], a: 0 },
      { q: 'Durga Puja is the grandest festival of…', o: ['Maharashtra', 'West Bengal', 'Rajasthan', 'Haryana'], a: 1 },
      { q: 'The Republic Day parade takes place in…', o: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'], a: 1 },
    ],
  },
}

// 5-letter answers for the Wordle-style game (common, friendly words)
export const WORDLE_WORDS = [
  'APPLE', 'BRAIN', 'CHAIR', 'DREAM', 'EARTH', 'FLAME', 'GRAPE', 'HEART', 'INDIA', 'JUICE',
  'KITES', 'LEMON', 'MANGO', 'NIGHT', 'OCEAN', 'PLANT', 'QUEEN', 'RIVER', 'SMILE', 'TIGER',
  'UNCLE', 'VOICE', 'WATER', 'YOUTH', 'ZEBRA', 'BREAD', 'CLOUD', 'DANCE', 'EAGLE', 'FRUIT',
  'GLASS', 'HONEY', 'LIGHT', 'MONEY', 'MUSIC', 'PAPER', 'PEARL', 'PLANE', 'POINT', 'POWER',
  'PRIDE', 'QUICK', 'RADIO', 'SLEEP', 'SPICE', 'STONE', 'STORM', 'SUGAR', 'TABLE', 'TRAIN',
  'TRUST', 'WHEAT', 'WORLD', 'WRITE', 'BEACH', 'CHESS', 'CROWN', 'DELHI', 'FIELD', 'GREEN',
  'HORSE', 'HOUSE', 'LOTUS', 'MARCH', 'MOUSE', 'NURSE', 'PEACE', 'PHONE', 'PIZZA', 'ROBOT',
  'SNAKE', 'SOUND', 'SPACE', 'SPORT', 'STARS', 'STEAM', 'STUDY', 'SWEET', 'TEACH', 'THINK',
]

// Word Bloom: make words from the 6 letters (each letter once per word).
// `words` is the accepted list for scoring.
export const BLOOM_PUZZLES = [
  { letters: ['E', 'A', 'R', 'T', 'H', 'S'], words: ['EARTH', 'HEART', 'HEARS', 'SHARE', 'SHEAR', 'RATES', 'STARE', 'TEARS', 'HATER', 'HATES', 'HEATS', 'EARS', 'EATS', 'RATS', 'STAR', 'HARE', 'HEAR', 'HEAT', 'RATE', 'SEAT', 'TEAR', 'EAST', 'ARTS', 'HATS'] },
  { letters: ['L', 'I', 'S', 'T', 'E', 'N'], words: ['LISTEN', 'SILENT', 'ENLIST', 'TINSEL', 'LINES', 'TILES', 'STILE', 'ISLET', 'INLET', 'LENS', 'LIST', 'TILE', 'LINE', 'NEST', 'TENS', 'SITE', 'TIES', 'SENT', 'TINS', 'NETS', 'LENT', 'LIES', 'NILE', 'SLIT'] },
  { letters: ['M', 'A', 'S', 'T', 'E', 'R'], words: ['MASTER', 'STREAM', 'TAMERS', 'MATES', 'TEAMS', 'STEAM', 'MEATS', 'RATES', 'STARE', 'TEARS', 'TAMER', 'SMART', 'TERMS', 'TRAMS', 'MARES', 'MAST', 'STEM', 'TEAM', 'MATE', 'MEAT', 'RATE', 'STAR', 'ARMS', 'RAMS', 'ARTS'] },
  { letters: ['P', 'L', 'A', 'N', 'E', 'T'], words: ['PLANET', 'PLANT', 'PLANE', 'PANEL', 'PETAL', 'PLEAT', 'LEAPT', 'PLATE', 'PANE', 'PLAN', 'TAPE', 'PEAT', 'LANE', 'LEAP', 'PALE', 'PLEA', 'NEAT', 'ANTE', 'TALE', 'LATE', 'LEAN', 'PANT', 'PEAL'] },
  { letters: ['D', 'A', 'N', 'C', 'E', 'R'], words: ['DANCER', 'DANCE', 'CANED', 'CEDAR', 'RACED', 'CRANE', 'CARED', 'CANE', 'CARD', 'DARE', 'DEAN', 'DEAR', 'EARN', 'NEAR', 'RACE', 'READ', 'ACRE', 'CARE', 'DARN', 'RAND'] },
  { letters: ['G', 'A', 'R', 'D', 'E', 'N'], words: ['GARDEN', 'DANGER', 'GANDER', 'RANGED', 'GRAND', 'GRADE', 'RANGE', 'ANGER', 'DARN', 'DEAR', 'EARN', 'NEAR', 'RANG', 'READ', 'GEAR', 'RAGE', 'DRAG', 'DARE', 'AGED', 'GRAN', 'DEAN'] },
  { letters: ['W', 'I', 'N', 'T', 'E', 'R'], words: ['WINTER', 'WRITE', 'TWINE', 'INTER', 'WREN', 'WINE', 'WIRE', 'TIER', 'TIRE', 'RENT', 'TWIN', 'WENT', 'NEWT', 'RITE', 'WRIT', 'TERN', 'TINE', 'REIN', 'WIT', 'TIN', 'NET', 'TIE', 'WIN'] },
  { letters: ['C', 'R', 'A', 'T', 'E', 'S'], words: ['CRATES', 'TRACES', 'REACTS', 'RECAST', 'CATER', 'CARTS', 'RACES', 'CARES', 'SCARE', 'TRACE', 'CRATE', 'REACT', 'ACRES', 'RATES', 'STARE', 'TEARS', 'CASE', 'CART', 'RACE', 'CARE', 'ACRE', 'EAST', 'SEAT', 'STAR'] },
]

// Guess the movie/thing from emojis (MCQ so no spelling fights)
export const EMOJI_RIDDLES = [
  { e: '🦁👑', o: ['Madagascar', 'The Lion King', 'Jungle Book', 'Zootopia'], a: 1 },
  { e: '🕷️🧑🗽', o: ['Batman', 'Ant-Man', 'Spider-Man', 'Venom'], a: 2 },
  { e: '🚢🧊💔', o: ['Life of Pi', 'Titanic', 'Poseidon', 'Jaws'], a: 1 },
  { e: '3️⃣🤪🎓', o: ['Munna Bhai MBBS', '3 Idiots', 'Student of the Year', 'Chhichhore'], a: 1 },
  { e: '🧙‍♂️⚡👓', o: ['Lord of the Rings', 'Harry Potter', 'Narnia', 'Doctor Strange'], a: 1 },
  { e: '🐼🥋🍜', o: ['Mulan', 'Kung Fu Panda', 'Karate Kid', 'Shang-Chi'], a: 1 },
  { e: '❄️👭⛄', o: ['Ice Age', 'Frozen', 'Happy Feet', 'Moana'], a: 1 },
  { e: '🦖🏝️🧬', o: ['King Kong', 'Jurassic Park', 'Godzilla', 'The Meg'], a: 1 },
  { e: '🚂💃🧔🌾', o: ['Jab We Met', 'DDLJ', 'Chennai Express', 'Barfi'], a: 1 },
  { e: '👽☎️🚲🌕', o: ['Avatar', 'E.T.', 'PK', 'Koi Mil Gaya'], a: 1 },
  { e: '🏏🇮🇳🏆🥇1983', o: ['Lagaan', '83', 'MS Dhoni', 'Iqbal'], a: 1 },
  { e: '🤡🎈🚿😱', o: ['Joker', 'It', 'The Mask', 'Annabelle'], a: 1 },
  { e: '🐠🔍🌊', o: ['Shark Tale', 'Finding Nemo', 'Moana', 'The Little Mermaid'], a: 1 },
  { e: '🦇🃏🌃', o: ['Iron Man', 'The Dark Knight', 'Deadpool', 'Watchmen'], a: 1 },
  { e: '🧸🚀♾️', o: ['Cars', 'Toy Story', 'Up', 'Coco'], a: 1 },
  { e: '👨‍🚀🕳️⏰🌽', o: ['Gravity', 'Interstellar', 'The Martian', 'Apollo 13'], a: 1 },
]
